stages:
    - test
    - report

variables:
  STAGE: prod

services:
  - docker:24.0.5-dind

run-tests:
    stage: test
    image: docker.24.0.5
    script:
        - docker compose up api-tests || true
    after_script:
        - docker compose up report
    artifacts:
      paths:
        - allure-report
      when: on_success
      expire_in: 10 days

pages:
    stage: report
    needs: 
        - run-tests
    script:
        - mkdir public
        - cp -r allure-report/* public
    artifacts:
      when: on_success
      expire_in: never
      paths:
        - public