stages:
    - tests
    - report

variables:
  STAGE: prod

services:
  - docker:24.0.5-dind

run_tests:
    stage: tests
<<<<<<< HEAD
    image: docker.24.0.5
=======
    image: docker:24.0.5
>>>>>>> 0a6ab78ab336ebd8a0722a7ea23ec1710952afe6
    script:
        - docker compose up api-tests || true
    after_script:
        - docker compose up report
    artifacts:
      paths:
        - allure-report
      when: on_success
      expire_in: 10 days

pages:
    stage: report
    needs: 
        - run_tests
    script:
        - mkdir public
        - cp -r allure-report/* public
    artifacts:
      when: on_success
      expire_in: never
      paths:
        - public